### ISSUE TITLE
mister.ini  not working 

### ISSUE THREAD

**Issue by suww37** [spark2k06/PCXT_MiSTer#12]
After PCXT core 20220523 update, [PCXT] setting in MISTER.ini is not recognized. I need to adjust the mister.ini settings because I need to use the lcd monitor connected to the io board vga 15pin port. Fix please.

**Comment by spark2k06** [comment]
Try the new release:

https://github.com/spark2k06/PCXT_MiSTer/blob/main/releases/PCXT_20220626.rbf

**Comment by suww37** [comment]
> Try the new release:
> 
> https://github.com/spark2k06/PCXT_MiSTer/blob/main/releases/PCXT_20220626.rbf


I tried to run PCXT beta 1.1 core, but as before, it failed to output from the lcd monitor connected to the vga port of the io board. Of course, the output to the HDMI port of the D-nano board works well. Perhaps my guess is that your lastest PCXT core doesn't allow individual settings in "mister.ini". Usually, individual settings for other cores of MiSTer are set by the sd card's core name(PCXT) in the "games" folder. Please check

**Comment by spark2k06** [comment]
With the configuration you suggest, specifically vga_scaler=1, for me it works better through the VGA output than before... since I didn't get the startup screen in CGA mode and now I do, I think it's a matter of your monitor, maybe some incompatibility with the resolution or the frequencies used by the Graphics Gremlin module.

**Comment by suww37** [comment]
> With the configuration you suggest, specifically vga_scaler=1, for me it works better through the VGA output than before... since I didn't get the startup screen in CGA mode and now I do, I think it's a matter of your monitor, maybe some incompatibility with the resolution or the frequencies used by the Graphics Gremlin module.

Thank you. I solved it by (mister.ini: vsync_adjust=0).
