### ISSUE TITLE
Filename is wrong

### ISSUE THREAD

**Issue by eubrunosilva** [spark2k06/PCXT_MiSTer#58]
Hi
when you download the file from http://www.retrowiki.es/download/file.php?id=20006264, the name is 000o001.zip and not jukost.zip

filename should be change in there different places:

https://github.com/spark2k06/PCXT_MiSTer/blob/dccab191393a85955daad1f9e309982197599a6d/SW/ROMs/make_rom_with_jukost.py#L8

https://github.com/spark2k06/PCXT_MiSTer/blob/dccab191393a85955daad1f9e309982197599a6d/SW/ROMs/make_rom_with_jukost.py#L10

https://github.com/spark2k06/PCXT_MiSTer/blob/dccab191393a85955daad1f9e309982197599a6d/SW/ROMs/make_rom_with_jukost.py#L14

maybe place the filename in a variable...

**Comment by spark2k06** [comment]
Precisely line 8 says to write it as jukost.zip, regardless of the original name... that's why, if you run it, you'll see that it works perfectly :-)

**Comment by eubrunosilva** [comment]
yes you are right... but first time i run it... it gave an error there ❌ 
well strange :)
