### ISSUE TITLE
Audio is choppy and cutting out with SBVGM and KQ1 (and others)

### ISSUE THREAD

**Issue by sofakng** [spark2k06/PCXT_MiSTer#70]
I'm using the Tandy mode with the latest PCXT core (20221015) with 14 MHz CPU speed and 921600 HDD but I've also tried slower speeds and the Tandy sound is cutting out and is choppy.

Video:  https://youtu.be/v8navlxabTI

Another discord user is reporting somewhat similar issues with Bubble Bobble but the audio going slow and then fast, etc.

**Comment by famiclone6502** [comment]
Yeah Bubble Bobble I'm playing with Tandy graphics/sound at 4.77 MHz with the slowest speed HDD. It plays like a warped record, fast and slow in a weird cycle. (Hint: The game does not run properly in Tandy mode with any UMB enabled).

**Comment by spark2k06** [comment]
I have no problem: https://youtu.be/sSJAOKP55Fc

Check your configuration, drivers and resident programs... I can't think of any other reason.

I've already commented it to other users, but for next time, run before the same tests with the same HD image in a real or emulated environment, such as PCem or 86Box selected the same machine (Tandy 1000, IBM5160...), very stable nowadays in the emulation of these machines.

Only if there are discrepancies, open an Issue but in the MiSTer-Devel repository:

https://github.com/MiSTer-devel/PCXT_MiSTer/issues

Thanks for your understanding.

Regarding the speed variability in Bubble Bobble music, this is an old acquaintance. Add the issue in the repository mentioned, for when we can find out why.
